#!/usr/bin/env python3

import sys
import os
import yaml

from pprint import pprint

JEKYLL_ROOT = os.getcwd()

# TODO: Change this to first read user input, then check _config.yml, then _config.toml
# Documentation: https://jekyllrb.com/docs/configuration/
try:
    JEKYLL_CONFIG_NAME = sys.argv[1]
except IndexError:
    JEKYLL_CONFIG_NAME = '_config.yml'

JEKYLL_CONFIG = os.path.join(JEKYLL_ROOT, JEKYLL_CONFIG_NAME)

if not os.path.isfile(JEKYLL_CONFIG_NAME):
    sys.stderr.write('Usage: {} [config-filename(if different)]\n'.format(sys.argv[0]))
    exit()

if os.path.dirname(JEKYLL_CONFIG) != os.path.dirname(JEKYLL_ROOT):
    # Change into the jekyll directory
    # NOTE: This always assumes that the config file is at the root of the jekyll directory
    # As per the documentation, this is not always the case: https://jekyllrb.com/docs/configuration/
    JEKYLL_ROOT = os.path.dirname(JEKYLL_CONFIG)

# This should always be correct, as per the documentation: https://jekyllrb.com/docs/posts/
JEKYLL_POSTS = os.path.join(JEKYLL_ROOT, '_posts')

class Manager:
    def __init__(self):
        with open(JEKYLL_CONFIG, 'r') as config_file:
            self.config = yaml.load(config_file, Loader=yaml.FullLoader)
        
        self.posts = list()
        for root,dir,posts in os.walk(JEKYLL_POSTS):
            for post in posts:
                self.posts.append(os.path.join(root, post))
        

    def start(self):
        # print(f"Config information for {self.config.get('title', 'Not Found')}:")
        # pprint(self.config)
        pprint(self.posts)
        pass

if __name__ == '__main__':
    m = Manager()
    m.start()
